services:
  mssql:
    container_name: mssql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrongRocks9151"
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P yourStrongRocks9151 -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    volumes:
      - /var/opt/mssql
  mongodb:
    container_name: mongoDb
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    container_name: rabbitMq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auctionService:
