name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "src/IdentityService/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/IdentityService/Dockerfile
          push: true
          tags: ssieverts/identity-svc:latest
